// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCtVkgE83s5jmYz-Nkw94dB594CmHJ-wI',
    appId: '1:719487465582:web:4286bef3f5c46372b0ce7f',
    messagingSenderId: '719487465582',
    projectId: 'loginkebo',
    authDomain: 'loginkebo.firebaseapp.com',
    storageBucket: 'loginkebo.appspot.com',
    measurementId: 'G-YQ6219FNSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVDOQnue0veTG97mvuOPKHW88oKC5yrc',
    appId: '1:719487465582:android:e74fbb0c3068024db0ce7f',
    messagingSenderId: '719487465582',
    projectId: 'loginkebo',
    storageBucket: 'loginkebo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyh4vB9Ze4u_CceMSm-t_tCLuyKCrCE34',
    appId: '1:719487465582:ios:3441396d44ed9ed0b0ce7f',
    messagingSenderId: '719487465582',
    projectId: 'loginkebo',
    storageBucket: 'loginkebo.appspot.com',
    iosBundleId: 'com.example.keboFlujo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyh4vB9Ze4u_CceMSm-t_tCLuyKCrCE34',
    appId: '1:719487465582:ios:3441396d44ed9ed0b0ce7f',
    messagingSenderId: '719487465582',
    projectId: 'loginkebo',
    storageBucket: 'loginkebo.appspot.com',
    iosBundleId: 'com.example.keboFlujo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCtVkgE83s5jmYz-Nkw94dB594CmHJ-wI',
    appId: '1:719487465582:web:d8bc8af3e7889424b0ce7f',
    messagingSenderId: '719487465582',
    projectId: 'loginkebo',
    authDomain: 'loginkebo.firebaseapp.com',
    storageBucket: 'loginkebo.appspot.com',
    measurementId: 'G-T0B2GK42QD',
  );
}
